analysis_with_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name ='login'),
    path('logout/', logout_view, name ='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from .views import (create_report_view,ReportListView,
                    render_pdf_view, ReportDetailView,UploadTemplateView,ReportDetailViewSecured,
                    csv_upload_view,assign_report)

app_name = 'reports'

urlpatterns = [
    path('',ReportListView.as_view(),name='main'),
    path('save/',create_report_view,name='create-report'),


    # To Upload EXcel File & Extract Excel Data
    path('upload/',csv_upload_view,name='upload'),

    # To Display DropZone JS
    path('from_file/',UploadTemplateView.as_view() ,name='from-file'),
    
    path('<pk>/',ReportDetailView.as_view(),name='detail'),
    path('<pk>/pdf/',render_pdf_view ,name='pdf-page'),

    path('assign_report/<int:pk>',assign_report ,name='assign'),
    path('assign_report/<int:pk>/<str:token>',ReportDetailViewSecured,name='secured_detail'),

]

sales/urls.py
from django.urls import include, path
from .views import (home_view, SaleListView,
                    SaleDetailView)

app_name = 'sales'

urlpatterns =[
    path('', home_view, name='home'),
    path('list/', SaleListView.as_view(), name='list'),
    path('list/<pk>/', SaleDetailView.as_view(), name='detail')
]

reports/models.py
from django.db import models
from profiles.models import Profile
from django.contrib.auth.models import User

from django.urls import reverse
# Create your models here.


class Report(models.Model):
    name= models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField(blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("reports:detail", kwargs={"pk": self.pk})
    
    
    def __str__(self):
        return str(self.name)
    
    class Meta:
        ordering = ('-created',)
    

'''
created
updated
assignedby USER
assignedto USER
reportno   REPORT
token      UUID

'''

class assign_peers(models.Model):
    assigned_by = models.ForeignKey(User, related_name="assigned_by", on_delete=models.CASCADE, blank=True, null=True)
    assigned_to = models.ForeignKey(User, related_name="assigned_to", on_delete=models.CASCADE, blank=True, null=True)
    token = models.CharField(default='', blank=True, null=True, max_length=500)
    report = models.ForeignKey(Report, on_delete=models.CASCADE, blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    notification = models.CharField(max_length=100,blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("reports:secured_detail", kwargs={"pk": self.report.id,"token": self.token})



    def __str__(self):
        return str(self.token)+':  '+str(self.assigned_by)+'[ > ]'+str(self.assigned_to)

reports/forms.py
from django import forms
from .models import Report

# Model Form | Very similar to model serializer
class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

reports/views.py
from django.shortcuts import render, get_object_or_404, redirect
from profiles.models import Profile
from django.http import JsonResponse
from .utils import get_report_image, remove_record
from .models import Report, assign_peers
from django.views.generic import ListView, DetailView, TemplateView


import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

from sales.models import Sale, Position, CSV
import csv
from django.utils.dateparse import parse_date
from products.models import Product
from customers.models import Customer

#  Protecting Function based Views using Decorators 
from django.contrib.auth.decorators import login_required
#  Protecting Class based Views using Mixins 
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid, random
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from analysis_with_django.settings import EMAIL_HOST_USER




@login_required
def ReportDetailViewSecured(request, pk, token):

    rep = Report.objects.get(pk=pk)


    if request.method == 'POST':
        print(request.POST)
        instance = assign_peers.objects.get(token = token, assigned_to = request.user, report = rep)
        instance.comments = request.POST.get('floatingTextarea2')
        instance.save()

        
    if assign_peers.objects.filter(token = token, assigned_to = request.user, report = rep).exists() or assign_peers.objects.filter(assigned_by = request.user).exists():

        qs = assign_peers.objects.filter(token = token, report = rep, assigned_by=request.user)


        for i in qs:
            i.notification="VIEWED"

        assign_peers.objects.bulk_update(qs, ['notification'])
        
        context ={
            'allow_view':True,
            'report_detail_obj':rep,
            'token':token,
            'all_comments':assign_peers.objects.filter(token = token, report = rep, comments__isnull= False),
            'request': request
        }

    else:
        context ={
                'allow_view':False
            }
    

    return render(request, 'reports/pvt_detail.html',context)





def assign_report(request,pk):
    if request.method == 'POST':

        print('request::>>', request.POST)

        
        if request.POST.get('operation',False):
            return remove_record(pk,request)


        if request.POST.getlist('emails') != []:
            
            print('request::>>', request.POST.getlist('emails'))


            if assign_peers.objects.filter(report_id=pk).exists():
                assign_peers.objects.filter(report_id=pk).delete()



            token_access = str(uuid.uuid4()).replace('-','').lower()[:12]+str(random.randint(0,9))

            # Objects for Bulk Create
            qs_objects = []

            for i in request.POST.getlist('emails'):
                print(i)
                qs_objects.append(
                    
                                assign_peers(
                                                assigned_by = request.user,
                                                assigned_to = User.objects.get(username = i),
                                                token = token_access,
                                                report = Report.objects.get(id=pk)
                                            )

                                )

            print(qs_objects)


            # Bulk Create
            assign_peers.objects.bulk_create(
                qs_objects
            )


            # Get reports obj

            report_obj = Report.objects.get(id=pk)
            access_lnk_peer_obj = assign_peers.objects.filter(token = token_access, report = report_obj).first()





            template_data = {
                'repno':report_obj.id,
                'name':report_obj.name,
                'remark':report_obj.remarks,
                'created':report_obj.created,

                # build_absolute_uri
                'access_link':request.build_absolute_uri(access_lnk_peer_obj.get_absolute_url()),
            }

            print('IMP TESTEST @@##$$', template_data)


            html_body= render_to_string('reports/assign_peer_emailtemp.html', template_data)

            msg = EmailMultiAlternatives(
                subject="Important! |  Invite to Peer Review the attached Sales Report.",

                body=html_body,

                # From Asigned by | Reply to Assigned By | to Assigned to

                from_email=EMAIL_HOST_USER,

                to=request.POST.getlist('emails'),

                reply_to=[EMAIL_HOST_USER],
            )

            msg.mixed_subtype = 'related'
            msg.attach_alternative(html_body, "text/html")

            msg.send()
        
        else:
            print('No Data')


    return JsonResponse({'msg':request.POST})




# For Dropzone
class UploadTemplateView(LoginRequiredMixin,TemplateView):
    template_name = 'reports/from_file.html'

# For Dropzone
@login_required
def csv_upload_view(request):
    print('@@@@@@@@@ File being sent')

    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')

        # Create CSV entries.
        obj, created = CSV.objects.get_or_create(file_name = csv_file_name)

        if created:
            obj.csv_file = csv_file
            obj.save()
            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)

                # To avoid the header row
                reader.__next__() 
                for row in reader:

                    transaction_id  = row[0]
                    product         = row[1]
                    quantity_no     = int(row[2])
                    customer        = row[3]

                    # DATE TO PARSE MUST BE YYYY-MM-DD Format
                    date            = parse_date(row[4])


                    '''
                    TASK 1

                    1. Create Products in DB from Excel Data, if not exist else continue
                    2. Create Customer bought Product Exist
                    3. Create Salesman
                    4. Create Position
                    5. Create Sales Instance
                    '''
                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    
                    # If Product instance for get() is None
                    except Product.DoesNotExist:
                        product_obj = None
                    
                    if product_obj is not None:
                        print('CUSTOMER', customer)
                        # _ = created. If doesn't exist & new created, then created = True
                        # Create the customer who's product exists.
                        customer_obj, _ = Customer.objects.get_or_create(name=customer)

                        # Current Logged-in User
                        salesman_obj = Profile.objects.get(user=request.user)

                        position_obj = Position.objects.create(
                            product = product_obj,
                            quantity = quantity_no,
                            created = date
                        )

                        # Due to Get or Create, the records are not repeated here.
                        sale_obj, _ = Sale.objects.get_or_create(
                            transaction_id = transaction_id,
                            customer = customer_obj,
                            salesman = salesman_obj,
                            created = date
                        )

                        # Updating Sale M2M Field
                        # Sale.Position field
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()

                return JsonResponse({'ex':False})
        else:
            return JsonResponse({'ex':True})


# Listing The Reports Created
class ReportListView(LoginRequiredMixin,ListView):
    model = Report
    template_name = 'reports/main.html'
    context_object_name = "report_list_obj"

    def get_context_data(self, **kwargs):
        context = super(ReportListView, self).get_context_data(**kwargs)

        all_report_ids = Report.objects.all().values_list('id')


        context.update({
            'assign_peers_qs': assign_peers.objects.filter(assigned_by=self.request.user,report_id__in=all_report_ids),
            'users': User.objects.all(),
            'notifications':assign_peers.objects.filter(assigned_by=self.request.user, report_id__in=all_report_ids, notification='NOTIFIED'),
        })

        print('MMYY KWARGS::>>', assign_peers.objects.filter(assigned_by=self.request.user, report_id__in=all_report_ids, notification='NOTIFIED'))
        return context

    
''' For above Class
def get_queryset(self):
        return CharacterSeries.objects.order_by('name')


        <<< ABOVE OP as of NOW >>> SAMPLE P TO LEARN >>>
        MMYY KWARGS::>> {'paginator': None, 'page_obj': None, 'is_paginated': False, 'object_list': <QuerySet [<Report: aknasbcjna>, <Report: This Report for Quaterly Months>, <Report: eewaawd>, 
        <Report: YOYYOYOYOOY>, <Report: dadad>, <Report: dadad>, <Report: dadad>, <Report: dadad>, <Report: adasas>, <Report: Test Report>]>, 'report_list_obj': <QuerySet [<Report: aknasbcjna>, 
        <Report: This Report for Quaterly Months>, <Report: eewaawd>, <Report: YOYYOYOYOOY>, 
        <Report: dadad>, <Report: dadad>, <Report: dadad>, <Report: dadad>, <Report: adasas>, <Report: Test Report>]>, 
        'view': <reports.views.ReportListView object at 0x0000020F8004D430>, 

reports/templates/reports/assign_peer_emailtemp.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>

        <b>Dear,</b><br>
        <p>
          Greetings!
           You have been invited to peer-review the Sales report.<br>
           <b>Please review the report by clicking the Secure link below</b>  
        </p><br><br>


        <table border 1>
            <thead>
              <tr>
                <th scope="col">Report No.</th>
                <th scope="col">Name</th>
                <th scope="col">Remark</th>
                <th scope="col">Created</th>
              </tr>
            </thead>
            <tbody>
        
              <tr>
                <td>
                    RepNo/{{repno}}
                </td>
                
                <td>{{name}}</td>
                                
                <td>{{remark}}</td>
        
                <td>{{created}}</td>
              </tr>
        
            
            </tbody>
          </table>
        
        <h1><a href={{access_link}}>Click here to Access Report</a></h1>
        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
    </body>
</html>

reports/templates/reports/detail.html
{% extends "base.html" %}

{% block title %}

{{report_detail_obj.name}}

{% endblock title %}


{% block content %}

{% if report_detail_obj.image %}

    <img src="{{report_detail_obj.image.url}}" alt="{{report_detail_obj.name}}"></img>

{% endif %}
    <br>
    <h3> Remarks </h3>
    {{report_detail_obj.remarks}}

    <hr>
    <p> author: {{report_detail_obj.author.user.username}}</p>
    <p> created: {{report_detail_obj.created}}</p>
{% endblock content %}

reports/templates/reports/from_file.html
{% extends 'base.html' %}

{% load static %}

{% block scripts %}

<script src="{% static 'reports/upload.js' %}" defer></script>

{% endblock scripts %}


{% block title %}
upload Sales Files
{% endblock title %}


{% block content %}

<h5> Upload your Sales Document</h5>

<br>

<div id="alert-box">
  
</div>

{% comment %}    dz is a class name given to identify styling {% endcomment %}

{% comment %} 

RESC:: 
https://docs.dropzone.dev/getting-started/setup/fallback-for-no-javascript

{% endcomment %}

<form id="my-dropzone" class="dropzone dz">
    {% csrf_token %}
    <div class="fallback">
      <input name="file" type="file" multiple />
    </div>
</form>

{% endblock content %}

reports/templates/reports/main.html
{% extends "base.html" %}


{% block title %}
Report Lists

{% endblock title %}


{% block content %}

{% comment %} <hr> {% endcomment %}





<table class="table table-bordered border-secondary main">
    <thead>
      <tr>
        <th scope="col">Report No.</th>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">Remark</th>
        <th scope="col">Created</th>
        <th scope="col">View PDF</th>
        <th scope="col">Detail</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in report_list_obj %}

      <tr id="row_{{obj.pk}}">
        <td>
            RepNo/{{obj.pk}}
        </td>
        <td>{{obj.name}}</td>
        

        
        {% if obj.image %}
        <td><img src="{{obj.image.url}}" class="card-img-top image-sm" alt="{{obj.name}}"></td>
        {%else%}
        <td>No Image</td>
        {% endif %}

        
        <td>{{obj.remarks|truncatewords:2}}</td>

        <td>{{obj.created|truncatewords:1}}</td>

        {% if obj.image %}
        <td><a href="{% url 'reports:pdf-page' obj.pk %}" class="btn btn-secondary">PDF</a></td>
        {%else%}
        <td><a href="#" class="btn btn-secondary disabled">PDF</a></td>
        {% endif %}

        
        <td><a href={{obj.get_absolute_url}} class="btn btn-primary">Details</a></td>

        {% comment %} <td><a href="{% url 'reports:delete' obj.pk %}" class="btn btn-danger">D</a></td> {% endcomment %}




      </tr>

    {% endfor %}
    
    </tbody>
  </table>





{% endblock content %}

reports/templates/reports/main_cop_270723.html
{% extends "base.html" %}

{% load static %}
{% block scripts %}
    <script src="{% static 'reports/tagInput.js' %}" defer></script>

{% endblock scripts %}


{% block title %}
Report Lists

{% endblock title %}


{% block content %}

{% comment %} <hr> {% endcomment %}


{% csrf_token %}


<table class="table table-bordered border-secondary main ml-1">
    <thead>
      <tr>
        <th scope="col">Report No.</th>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">Remark</th>
        <th scope="col">Created</th>
        <th scope="col">View PDF</th>
        <th scope="col">Detail</th>
        <th scope="col">Assign Reviewers</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in report_list_obj %}

      <tr id="row_{{obj.pk}}">
        <td>
            RepNo/{{obj.pk}}
        </td>
        <td>{{obj.name}}</td>
        

        
        {% if obj.image %}
        <td><img src="{{obj.image.url}}" class="card-img-top image-sm" alt="{{obj.name}}"></td>
        {%else%}
        <td>No Image</td>
        {% endif %}

        
        <td>{{obj.remarks|truncatewords:2}}</td>

        <td>{{obj.created|truncatewords:1}}</td>

        {% if obj.image %}
        <td><a href="{% url 'reports:pdf-page' obj.pk %}" class="btn btn-secondary">PDF</a></td>
        {%else%}
        <td><a href="#" class="btn btn-secondary disabled">PDF</a></td>
        {% endif %}

        
        <td><a href={{obj.get_absolute_url}} class="btn btn-primary">Details</a></td>

        {% comment %} <td><a href="{% url 'reports:delete' obj.pk %}" class="btn btn-danger">D</a></td> {% endcomment %}


        <td>
          <div class="tags-input">
            <ul id="tags_{{obj.pk}}">

              {% for ap in assign_peers_qs %}

                {% if ap.report.id == obj.pk %}

                  {% if ap.assigned_to %}

                    
                    <li>{{ap.assigned_to.username}}<button class="delete-button" onclick="tag_remove(`{{obj.pk}}`)">X</button></li>

                  {% endif %}
                
                {% endif %}
              
              {% endfor %}

            </ul>
            <input type="text" id="input-tag_{{obj.pk}}" placeholder="Enter Emails" required autocomplete="off" onfocus="printID(`{{obj.pk}}`)"/>
            <input type="submit" id="button-tag_{{obj.pk}}" class="btn btn-warning" autocomplete="off" value="Assign"/>
          </div>

        </td>


      </tr>

    {% endfor %}
    
    </tbody>
  </table>





{% endblock content %}

reports/templates/reports/notification_emailtemp.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <style>
            .body{
                background-color: yellow;
            }
            </style>
    </head>

    
    <body class="body">
        <p>
            <h2><a href='http://127.0.0.1:8000{{insobj.get_absolute_url}}'>Some one is talking here, Click the link and view reponses</a><h2>
            <h3>Talks about Report {{insobj.report.id}} - {{insobj.report.name}}</h3>

            <table>
                <tr>
                    {{insobj.assigned_to}}

                    <p>
                        {{insobj.comments | truncatewords:4}}
                    </p>
                <tr>
            </table>
        </p><br><br>
        
        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
    </body>
</html>

reports/templates/reports/pdf.html
!<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PDF {{obj.name}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            .image {
                width: 100%;
                height: auto;
            }
        </style>
    </head>
    <body>

        <h1>{{obj.name}}</h1>
        <hr>
        <img src="{{obj.image.path}}" class="image">
        <br>


        <h3> Remarks</h3>
        <p>{{obj.remarks}}</p>

        <hr>
        <p> author: <b>{{obj.author.user.username}}</b></p>
        <p> created: <b>{{obj.created}}</b></p>
    </body>
</html>

reports/templates/reports/pvt_detail.html
{% extends "base.html" %}


    {% block title %}

    {{report_detail_obj.name}}

    {% endblock title %}


    {% block content %}

    {% if allow_view %}

        {% if report_detail_obj.image %}

            <img src="{{report_detail_obj.image.url}}" alt="{{report_detail_obj.name}}"></img>

        {% endif %}
            <br>
            <h3> Remarks </h3>
            {{report_detail_obj.remarks}}

            <hr>
            <p> author: {{report_detail_obj.author.user.username}}</p>
            <p> created: {{report_detail_obj.created}}</p>
    
            <br>
            <hr>
            <h3>Opinions / Reviews / Actions</h3><br>

            <form action="{% url 'reports:secured_detail' pk=report_detail_obj.id token=token %}" method="post">

                {% csrf_token %}
                <div class="form-floating">
                
                    <textarea class="form-control" id="floatingTextarea2" name="floatingTextarea2" style="height: 100px"></textarea>
                    <label for="floatingTextarea2">Opinions / Reviews / Actions</label>
                </div>

                <button type="submit" class="btn btn-primary mt-3">Post</button>
            </form>

            <br><hr>
            <h3>Peers' Space</h3>

            {% if all_comments %}

                {% for comment in all_comments %}
                
                    <div class="card" style="width: 50em;">
                        <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-body-secondary">{{comment.assigned_to}} </h6>
                        <p class="card-text">{{comment.comments|safe}}</p>
                        </div>
                    </div>

                {% endfor %}

            {% else %}
                    Nothing here | Post your's now

            {% endif %}



  
    {% else %}
    <div class="alert alert-danger" role="alert">
        <h2>The Link seems to be broken or You have no privileges. <br>
            Please contact the administrator
        </h2>
    </div>

    {% endif %}
    {% endblock content %}